name: flowr_root
channels:
  - pytorch
  - nvidia
  - conda-forge
  - schrodinger
  - mx
dependencies:
  # Core Python
  - python=3.12.12
  - pip
  - setuptools=80.9.0
  
  # PyTorch ecosystem (install first from pytorch channel)
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchtriton=3.1.0
  
  # CUDA toolkit
  - conda-forge::cudatoolkit=11.8.0
  
  # Scientific computing
  - conda-forge::numpy=1.26.4
  - conda-forge::scipy=1.16.3
  - conda-forge::pandas=2.3.3
  - conda-forge::scikit-learn=1.8.0
  
  # Visualization
  - conda-forge::matplotlib=3.10.8
  - conda-forge::seaborn=0.13.2
  - conda-forge::py3dmol=2.5.3
  - conda-forge::nglview=4.0
  
  # Jupyter
  - conda-forge::notebook=7.5.1
  - conda-forge::jupyter
  - conda-forge::jupyterlab=4.5.1
  
  # Chemistry & Molecular modeling
  - conda-forge::rdkit=2025.03.6
  - conda-forge::openbabel=3.1.1
  - conda-forge::openmm=8.2.0
  - conda-forge::openff-toolkit=0.18.0
  - conda-forge::openmmforcefields=0.15.0
  - conda-forge::pdbfixer=1.12
  - conda-forge::vina=1.2.6
  - conda-forge::xtb=6.7.1
  - conda-forge::ambertools=24.8
  
  # Bioinformatics
  - conda-forge::biopython=1.86
  - conda-forge::mdanalysis=2.10.0
  - conda-forge::prody=2.6.1
  - conda-forge::datamol=0.12.5
  - conda-forge::pypdb=2.4
  
  # ML & Deep Learning utilities
  - conda-forge::lightning=2.6.0
  - conda-forge::torchmetrics=1.8.2
  
  # Other utilities
  - conda-forge::packaging=25.0
  - conda-forge::pyyaml=6.0.3
  - conda-forge::h5py=3.15.1
  - conda-forge::lxml=6.0.2
  - conda-forge::networkx=3.6.1
  - conda-forge::tqdm=4.67.1
  - conda-forge::joblib=1.5.3
  - conda-forge::filelock=3.20.1
  
  # Schrodinger channel
  - schrodinger::pymol-bundle=3.1.6.1
  
  # MX channel
  - mx::reduce=3.24
  
  # Pip packages
  - pip:
      - lmdb==1.7.5
      - rmsd==1.6.4
      - torch_ema==0.3
      - meeko==0.7.1
      - hydride==1.2.3
      - biotite==1.5.0
      - prolif==2.0.3
      - pdbinf==0.0.4
      - mlflow==3.7.0
      - biopandas==0.5.1
      - torch_geometric==2.7.0
      - tensordict==0.10.0
      - gemmi==0.7.4