name: flowr_root
channels:
  - pytorch
  - conda-forge
dependencies:
  # Core Python
  - python=3.11.14
  - pip
  - setuptools=80.9.0
  
  # PyTorch (CPU for macOS)
  - pytorch::pytorch=2.5.1
  
  # Scientific computing
  - conda-forge::numpy=1.26.4
  - conda-forge::scipy=1.16.3
  - conda-forge::pandas=2.3.3
  - conda-forge::scikit-learn=1.3.1
  
  # Visualization
  - conda-forge::matplotlib=3.10.8
  - conda-forge::seaborn=0.13.2
  - conda-forge::py3dmol=2.5.3
  - conda-forge::nglview=4.0
  
  # Jupyter
  - conda-forge::notebook=7.5.1
  - conda-forge::jupyter
  - conda-forge::jupyterlab=4.5.1
  
  # Chemistry & Molecular modeling
  - conda-forge::openbabel=3.1.1
  - conda-forge::openmm=8.4.0
  - conda-forge::openff-toolkit=0.18.0
  - conda-forge::pdbfixer=1.12
  - conda-forge::vina=1.2.5
  - conda-forge::xtb=6.6.0
  - conda-forge::ambertools=23.3
  
  # Bioinformatics
  - conda-forge::biopython=1.86
  - conda-forge::mdanalysis=2.10.0
  - conda-forge::prody=2.4.1
  - conda-forge::datamol=0.12.5
  - conda-forge::pypdb=2.4
  
  # ML & Deep Learning utilities
  - conda-forge::lightning=2.6.0
  - conda-forge::torchmetrics=1.8.2
  
  # Molecular visualization
  - conda-forge::pymol-open-source=3.1.0
  
  # Other utilities
  - conda-forge::packaging=25.0
  - conda-forge::pyyaml=6.0.3
  - conda-forge::h5py=3.15.1
  - conda-forge::lxml
  - conda-forge::networkx=3.6.1
  - conda-forge::tqdm=4.67.1
  - conda-forge::joblib=1.5.3
  - conda-forge::filelock=3.20.1
  
  # Pip packages
  - pip:
      - lmdb==1.7.5
      - rmsd==1.6.4
      - torch_ema==0.3
      - hydride==1.2.3
      - biotite==1.5.0
      - prolif==2.0.3
      - wandb==0.23.1
      - pdbinf==0.0.4
      - mlflow==3.7.0
      - biopandas==0.5.1
      - torch_geometric==2.7.0
      - tensordict==0.10.0
      - gemmi==0.7.4
      - rdkit==2025.9.3
